### ISSUE TITLE
Cannot login via LDAP

### ISSUE THREAD

**Issue by zer0brain** [adfinis-sygroup/vault-client#34]
Operating System: lubuntu 16.04

If i try to login via LDAP the following error occurs:
```
Username: Foobar
Password: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x748264]

goroutine 1 [running]:
main.GetAuthenticationToken(0x9cbee0, 0xc4200158f0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/adfinis-sygroup/vault-client/src/auth.go:40 +0x1a4
main.(*LoginCommand).Run(0xc420013c30, 0xc42000c4b0, 0x0, 0x0, 0xc420013bf0)
	/home/travis/gopath/src/github.com/adfinis-sygroup/vault-client/src/login.go:34 +0x42e
github.com/mitchellh/cli.(*CLI).Run(0xc4200d2180, 0x0, 0x410e28, 0x0)
	/home/travis/gopath/src/github.com/adfinis-sygroup/vault-client/src/github.com/mitchellh/cli/cli.go:160 +0x1cc
main.main()
	/home/travis/gopath/src/github.com/adfinis-sygroup/vault-client/src/main.go:32 +0x6f


```

**Comment by winpat** [comment]
I will have a look at this. Thanks for reporting.

**Comment by winpat** [comment]
I could reproduce the bug. The fix is in progress (https://github.com/adfinis-sygroup/vault-client/pull/35).

**Comment by winpat** [comment]
Bug is fixed.
